## Spring MongoDB Connection
spring:
  data:
    mongodb:
      uri: <TODO> # add mongodb connection url here

## Swagger UI
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs

